services:
  postgres:
    ports:
      - "5434:5432"
    volumes:
      - ./backups:/backups

  api:
    command: npm start
    ports:
      - "127.0.0.1:5001:5000"
    volumes:
      - /var/www/vhosts/mobiliti.at/httpdocs/dashboard/backend/public/directory_logos:/app/public/directory_logos
      - /var/www/vhosts/mobiliti.at/httpdocs/dashboard/backend/public/logos:/app/public/logos

  worker-ai:
    command: npm run start:ai

  worker-scrape:
    command: npm run start:scrape

  worker-mail:
    command: npm run start:mail

  worker-data:
    command: npm run start:data

  worker-funding:
    command: npm run start:funding