// /var/www/vhosts/mobiliti.at/httpdocs/dashboard/ecosystem.config.js
module.exports = {
  apps: [
    // --- API ---
    {
      name: "api",
      cwd: "/var/www/vhosts/mobiliti.at/httpdocs/dashboard",
      script: "backend/server.js",
      exec_mode: "fork",
      instances: 1,
      watch: false,
      env: {
        NODE_ENV: "development"
      },
      env_production: {
        NODE_ENV: "production",
        HOST: "127.0.0.1",        
        PORT: 5000,
        DB_USER: "admin-mobiliti",
        DB_HOST: "localhost",
        DB_DATABASE: "dashboard-mobiliti",
        DB_PASSWORD: "XX.XX-XX",
        DB_PORT: 5432,
        OPENAI_API_KEY:"XX.XX-XX",
        REDIS_URL: "redis://127.0.0.1:32770",
        EMAIL_HOST: "smtp.strato.de",
        EMAIL_PORT: 587,
        EMAIL_USER: "sp@mobiliti.at",
        EMAIL_PASS: "XX.XX-XX",
        EMAIL_ADMIN: "Admin Dashboard <hello@mobiliti.at>",
        REDIS_HOST: "127.0.0.1",
        REDIS_PORT: 32770,
        JWT_SECRET: "XX.XX-XX",
        GOOGLE_GEMINI_API_KEY: "XX.XX-XX",
        GOOGLE_API_KEY: "XX.XX-XX",
        GOOGLE_CX_ID: "a0a400116d8d247fc",
        GOOGLE_CLIENT_ID: "64253350842-rsbufoutiov8pcoo19nedhdjgrn5d76e.apps.googleusercontent.com",
        GOOGLE_CLIENT_SECRET: "XX.XX-XX",
        OPENCHARGEMAP_API_KEY: "XX.XX-XX",
        SESSION_SECRET: "XX.XX-XX",
        AWS_ACCESS_KEY_ID: "XX.XX-XX",
        AWS_SECRET_ACCESS_KEY: "XX.XX-XX",
        AWS_S3_REGION: "eu-central-1",
        AWS_S3_BUCKET_NAME: "mobiliti-dashboard-uploads",
        TANKERKOENIG_API_KEY: "XX.XX-XX",
        ECONTROL_API_KEY: "XXX",
        METALPRICE_API_KEY: "XX.XX-XX",
        OILPRICE_API_KEY: "XX.XX-XX",
        CO2_API_KEY: "xxx",
        YOUTUBE_API_KEY: "XX.XX-XX",
        LADESTELLEN_AT_KEY: "XX.XX-XX",
        YOUTUBE_API_KEY: "XX.XX-XX"
      }
    },

    // --- Worker: AI ---
    {
      name: "aiWorker",
      cwd: "/var/www/vhosts/mobiliti.at/httpdocs/dashboard",
      script: "backend/workers/aiWorker.js",
      exec_mode: "fork",
      instances: 1,
      watch: false,
      env: {
        NODE_ENV: "development"
      },
      env_production: {
        NODE_ENV: "production",
        HOST: "127.0.0.1",        
        PORT: 5000,
        DB_USER: "admin-mobiliti",
        DB_HOST: "localhost",
        DB_DATABASE: "dashboard-mobiliti",
        DB_PASSWORD: "XX.XX-XX",
        DB_PORT: 5432,
        OPENAI_API_KEY:"XX.XX-XX",
        REDIS_URL: "redis://127.0.0.1:32770",
        EMAIL_HOST: "smtp.strato.de",
        EMAIL_PORT: 587,
        EMAIL_USER: "sp@mobiliti.at",
        EMAIL_PASS: "XX.XX-XX",
        EMAIL_ADMIN: "Admin Dashboard <hello@mobiliti.at>",
        REDIS_HOST: "127.0.0.1",
        REDIS_PORT: 32770,
        JWT_SECRET: "XX.XX-XX",
        GOOGLE_GEMINI_API_KEY: "XX.XX-XX",
        GOOGLE_API_KEY: "XX.XX-XX",
        GOOGLE_CX_ID: "a0a400116d8d247fc",
        GOOGLE_CLIENT_ID: "64253350842-rsbufoutiov8pcoo19nedhdjgrn5d76e.apps.googleusercontent.com",
        GOOGLE_CLIENT_SECRET: "XX.XX-XX",
        OPENCHARGEMAP_API_KEY: "XX.XX-XX",
        SESSION_SECRET: "XX.XX-XX",
        AWS_ACCESS_KEY_ID: "XX.XX-XX",
        AWS_SECRET_ACCESS_KEY: "XX.XX-XX",
        AWS_S3_REGION: "eu-central-1",
        AWS_S3_BUCKET_NAME: "mobiliti-dashboard-uploads",
        TANKERKOENIG_API_KEY: "XX.XX-XX",
        ECONTROL_API_KEY: "XXX",
        METALPRICE_API_KEY: "XX.XX-XX",
        OILPRICE_API_KEY: "XX.XX-XX",
        CO2_API_KEY: "xxx",
        YOUTUBE_API_KEY: "XX.XX-XX",
        LADESTELLEN_AT_KEY: "XX.XX-XX",
        YOUTUBE_API_KEY: "XX.XX-XX"
      }
    },

    // --- Worker: Scrape ---
    {
      name: "scrapeWorker",
      cwd: "/var/www/vhosts/mobiliti.at/httpdocs/dashboard",
      script: "backend/workers/scrapeWorker.js",
      exec_mode: "fork",
      instances: 1,
      env: {
        NODE_ENV: "development"
      },
      env_production: {
        NODE_ENV: "production",
        HOST: "127.0.0.1",        
        PORT: 5000,
        DB_USER: "admin-mobiliti",
        DB_HOST: "localhost",
        DB_DATABASE: "dashboard-mobiliti",
        DB_PASSWORD: "XX.XX-XX",
        DB_PORT: 5432,
        OPENAI_API_KEY:"XX.XX-XX",
        REDIS_URL: "redis://127.0.0.1:32770",
        EMAIL_HOST: "smtp.strato.de",
        EMAIL_PORT: 587,
        EMAIL_USER: "sp@mobiliti.at",
        EMAIL_PASS: "XX.XX-XX",
        EMAIL_ADMIN: "Admin Dashboard <hello@mobiliti.at>",
        REDIS_HOST: "127.0.0.1",
        REDIS_PORT: 32770,
        JWT_SECRET: "XX.XX-XX",
        GOOGLE_GEMINI_API_KEY: "XX.XX-XX",
        GOOGLE_API_KEY: "XX.XX-XX",
        GOOGLE_CX_ID: "a0a400116d8d247fc",
        GOOGLE_CLIENT_ID: "64253350842-rsbufoutiov8pcoo19nedhdjgrn5d76e.apps.googleusercontent.com",
        GOOGLE_CLIENT_SECRET: "XX.XX-XX",
        OPENCHARGEMAP_API_KEY: "XX.XX-XX",
        SESSION_SECRET: "XX.XX-XX",
        AWS_ACCESS_KEY_ID: "XX.XX-XX",
        AWS_SECRET_ACCESS_KEY: "XX.XX-XX",
        AWS_S3_REGION: "eu-central-1",
        AWS_S3_BUCKET_NAME: "mobiliti-dashboard-uploads",
        TANKERKOENIG_API_KEY: "XX.XX-XX",
        ECONTROL_API_KEY: "XXX",
        METALPRICE_API_KEY: "XX.XX-XX",
        OILPRICE_API_KEY: "XX.XX-XX",
        CO2_API_KEY: "xxx",
        YOUTUBE_API_KEY: "XX.XX-XX",
        LADESTELLEN_AT_KEY: "XX.XX-XX",
        YOUTUBE_API_KEY: "XX.XX-XX"
      }
    },

    // --- Worker: E-Mail ---
    {
      name: "emailWorker",
      cwd: "/var/www/vhosts/mobiliti.at/httpdocs/dashboard",
      script: "backend/workers/emailWorker.js",
      exec_mode: "fork",
      instances: 1,
      env: {
        NODE_ENV: "development"
      },
      env_production: {
        NODE_ENV: "production",
        HOST: "127.0.0.1",        
        PORT: 5000,
        DB_USER: "admin-mobiliti",
        DB_HOST: "localhost",
        DB_DATABASE: "dashboard-mobiliti",
        DB_PASSWORD: "XX.XX-XX",
        DB_PORT: 5432,
        OPENAI_API_KEY:"XX.XX-XX",
        REDIS_URL: "redis://127.0.0.1:32770",
        EMAIL_HOST: "smtp.strato.de",
        EMAIL_PORT: 587,
        EMAIL_USER: "sp@mobiliti.at",
        EMAIL_PASS: "XX.XX-XX",
        EMAIL_ADMIN: "Admin Dashboard <hello@mobiliti.at>",
        REDIS_HOST: "127.0.0.1",
        REDIS_PORT: 32770,
        JWT_SECRET: "XX.XX-XX",
        GOOGLE_GEMINI_API_KEY: "XX.XX-XX",
        GOOGLE_API_KEY: "XX.XX-XX",
        GOOGLE_CX_ID: "a0a400116d8d247fc",
        GOOGLE_CLIENT_ID: "64253350842-rsbufoutiov8pcoo19nedhdjgrn5d76e.apps.googleusercontent.com",
        GOOGLE_CLIENT_SECRET: "XX.XX-XX",
        OPENCHARGEMAP_API_KEY: "XX.XX-XX",
        SESSION_SECRET: "XX.XX-XX",
        AWS_ACCESS_KEY_ID: "XX.XX-XX",
        AWS_SECRET_ACCESS_KEY: "XX.XX-XX",
        AWS_S3_REGION: "eu-central-1",
        AWS_S3_BUCKET_NAME: "mobiliti-dashboard-uploads",
        TANKERKOENIG_API_KEY: "XX.XX-XX",
        ECONTROL_API_KEY: "XXX",
        METALPRICE_API_KEY: "XX.XX-XX",
        OILPRICE_API_KEY: "XX.XX-XX",
        CO2_API_KEY: "xxx",
        YOUTUBE_API_KEY: "XX.XX-XX",
        LADESTELLEN_AT_KEY: "XX.XX-XX",
        YOUTUBE_API_KEY: "XX.XX-XX"
      }
    },

    // --- Worker: Data Update ---
    {
      name: "dataUpdateWorker",
      cwd: "/var/www/vhosts/mobiliti.at/httpdocs/dashboard",
      script: "backend/workers/dataUpdateWorker.js",
      exec_mode: "fork",
      instances: 1,
      env: {
        NODE_ENV: "development"
      },
      env_production: {
        NODE_ENV: "production",
        HOST: "127.0.0.1",        
        PORT: 5000,
        DB_USER: "admin-mobiliti",
        DB_HOST: "localhost",
        DB_DATABASE: "dashboard-mobiliti",
        DB_PASSWORD: "XX.XX-XX",
        DB_PORT: 5432,
        OPENAI_API_KEY:"XX.XX-XX",
        REDIS_URL: "redis://127.0.0.1:32770",
        EMAIL_HOST: "smtp.strato.de",
        EMAIL_PORT: 587,
        EMAIL_USER: "sp@mobiliti.at",
        EMAIL_PASS: "XX.XX-XX",
        EMAIL_ADMIN: "Admin Dashboard <hello@mobiliti.at>",
        REDIS_HOST: "127.0.0.1",
        REDIS_PORT: 32770,
        JWT_SECRET: "XX.XX-XX",
        GOOGLE_GEMINI_API_KEY: "XX.XX-XX",
        GOOGLE_API_KEY: "XX.XX-XX",
        GOOGLE_CX_ID: "a0a400116d8d247fc",
        GOOGLE_CLIENT_ID: "64253350842-rsbufoutiov8pcoo19nedhdjgrn5d76e.apps.googleusercontent.com",
        GOOGLE_CLIENT_SECRET: "XX.XX-XX",
        OPENCHARGEMAP_API_KEY: "XX.XX-XX",
        SESSION_SECRET: "XX.XX-XX",
        AWS_ACCESS_KEY_ID: "XX.XX-XX",
        AWS_SECRET_ACCESS_KEY: "XX.XX-XX",
        AWS_S3_REGION: "eu-central-1",
        AWS_S3_BUCKET_NAME: "mobiliti-dashboard-uploads",
        TANKERKOENIG_API_KEY: "XX.XX-XX",
        ECONTROL_API_KEY: "XXX",
        METALPRICE_API_KEY: "XX.XX-XX",
        OILPRICE_API_KEY: "XX.XX-XX",
        CO2_API_KEY: "xxx",
        YOUTUBE_API_KEY: "XX.XX-XX",
        LADESTELLEN_AT_KEY: "XX.XX-XX",
        YOUTUBE_API_KEY: "XX.XX-XX"
      }
    },
    // --- Worker: Funding Extraction ---
    {
      name: "fundingWorker",
      cwd: "/var/www/vhosts/mobiliti.at/httpdocs/dashboard",
      script: "backend/workers/fundingWorker.js",
      exec_mode: "fork",
      instances: 1,
      env: {
        NODE_ENV: "development"
      },
      env_production: {
        NODE_ENV: "production",
        HOST: "127.0.0.1",        
        PORT: 5000,
        DB_USER: "admin-mobiliti",
        DB_HOST: "localhost",
        DB_DATABASE: "dashboard-mobiliti",
        DB_PASSWORD: "XX.XX-XX",
        DB_PORT: 5432,
        OPENAI_API_KEY:"XX.XX-XX",
        REDIS_URL: "redis://127.0.0.1:32770",
        EMAIL_HOST: "smtp.strato.de",
        EMAIL_PORT: 587,
        EMAIL_USER: "sp@mobiliti.at",
        EMAIL_PASS: "XX.XX-XX",
        EMAIL_ADMIN: "Admin Dashboard <hello@mobiliti.at>",
        REDIS_HOST: "127.0.0.1",
        REDIS_PORT: 32770,
        JWT_SECRET: "XX.XX-XX",
        GOOGLE_GEMINI_API_KEY: "XX.XX-XX",
        GOOGLE_API_KEY: "XX.XX-XX",
        GOOGLE_CX_ID: "a0a400116d8d247fc",
        GOOGLE_CLIENT_ID: "64253350842-rsbufoutiov8pcoo19nedhdjgrn5d76e.apps.googleusercontent.com",
        GOOGLE_CLIENT_SECRET: "XX.XX-XX",
        OPENCHARGEMAP_API_KEY: "XX.XX-XX",
        SESSION_SECRET: "XX.XX-XX",
        AWS_ACCESS_KEY_ID: "XX.XX-XX",
        AWS_SECRET_ACCESS_KEY: "XX.XX-XX",
        AWS_S3_REGION: "eu-central-1",
        AWS_S3_BUCKET_NAME: "mobiliti-dashboard-uploads",
        TANKERKOENIG_API_KEY: "XX.XX-XX",
        ECONTROL_API_KEY: "XXX",
        METALPRICE_API_KEY: "XX.XX-XX",
        OILPRICE_API_KEY: "XX.XX-XX",
        CO2_API_KEY: "xxx",
        YOUTUBE_API_KEY: "XX.XX-XX",
        LADESTELLEN_AT_KEY: "XX.XX-XX",
        YOUTUBE_API_KEY: "XX.XX-XX"
      }
    },        
  ]
};


