const express = require('express');
const router = express.Router();
const authMiddleware = require('../middleware/authMiddleware');
const dataController = require('../controllers/dataController');

router.use(authMiddleware);

router.get('/relevant-action', dataController.getRelevantAction);
router.get('/search', dataController.globalSearch);
router.post('/ai-ask', dataController.handleAiQuestion);
router.get('/fuel/search', dataController.fuelSearch);
router.post('/fuel/prices-by-ids', dataController.getPricesByIds);
router.get('/commodities', dataController.getCommodityPrices);
router.get('/traffic-info', dataController.getTrafficInfo);
router.get('/ai-content', dataController.getAiContent);
router.get('/scraped-content', dataController.getScrapedContent);
router.get('/scraped-content-counts', dataController.getScrapedContentCounts);
router.get('/tax-changes', dataController.getTaxChanges);
// router.get('/fleet-news', dataController.getFleetAssociationNews);
router.get('/traffic-regions', dataController.getUniqueTrafficRegions);
router.get('/bp-scraped-content', dataController.getBpScrapedContent);
router.get('/vignettes', dataController.getVignettePrices);
router.post('/content/:contentId/vote', dataController.voteOnContent);
router.post('/content/:contentId/mark-as-read', dataController.markContentAsRead);
router.post('/generate-email', authMiddleware, dataController.generateEmailFromContent);
router.get('/user-stats/:bpId', authMiddleware, dataController.getBusinessPartnerUserStatsForUser);
router.get('/ai-prompt-rules', authMiddleware, dataController.getAIPromptRulesForUser);
router.get('/categories', authMiddleware, dataController.getCategoriesForUser);
router.get('/regions', dataController.getAllRegions);
router.get('/ev-stations', authMiddleware, dataController.getEVStations);
router.get('/ev/search', dataController.evStationSearch);
router.post('/scraped-content/:contentId/mark-as-read', dataController.markScrapedContentAsRead);
router.post('/share-content-by-email', authMiddleware, dataController.shareContentByEmail);
router.get('/vignette-countries', dataController.getVignetteCountries);
router.get('/commodities/history', dataController.getCommodityHistory);
router.get('/calendar-events', authMiddleware, dataController.getCalendarEvents);
router.get('/enhanced-calendar-events', authMiddleware, dataController.getEnhancedCalendarEvents);
router.get('/holidays', authMiddleware, dataController.getPublicHolidays);
router.post('/events/:eventId/vote', authMiddleware, dataController.voteOnEventAttendance);
router.post('/events/share', authMiddleware, dataController.shareEventByEmail);
router.get('/dashboard/config', dataController.getDashboardConfig);
router.get('/actions', authMiddleware, dataController.getActiveActionsForWidget);
router.get('/active-advertisement', dataController.getActiveAdvertisement);
router.get('/tags', dataController.getTagsForCategory);
router.get('/all-tags', dataController.getAllTags);
router.get('/events', authMiddleware, dataController.getEvents);
router.get('/economic-statistics', dataController.getEconomicStatistics);
router.get('/economic-statistics/countries', dataController.getUniqueStatCountries);
router.post('/generate-draft-from-content', dataController.generateDraftFromContent);
router.get('/account-intelligence', dataController.getAccountIntelligence);
router.get('/daily-briefing', dataController.getDailyBriefing);
router.get('/notifications/count', dataController.getNotificationCounts);
router.get('/monitor-entries', dataController.getMonitorEntries);
router.get('/bp-members-preview', dataController.getBusinessPartnerMembersPreview);
router.get('/daily-briefing', authMiddleware, dataController.getDailyBriefing);
router.get('/daily-briefing/pdf', dataController.getDailyBriefingPdfByToken);

router.get('/sentiment', dataController.getMarketSentiment);
router.post('/sentiment/vote', dataController.voteSentiment);

module.exports = router;